name: Tests with tox

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox -U
    - name: Run Tests
      run: |
        export PYTHONPATH="${{ github.workspace }}"
        tox -r -vvv
    - name: Run Test using PyTest
      run: |
        pip install .[dev]
        python -m pytest .
